### ISSUE TITLE
Supplying custom data readers to defconfig

### ISSUE THREAD

**Issue by lloydshark** [james-henderson/nomad#18]
I'd like to optionally be able to supply custom data readers when specifying my config.

So the use of defconfig might look like the following.

```
(defn my-custom-reader [form]
  :some-other-value)

(defconfig my-configuration (io/resource "config.edn")
           :data-readers {'custom/my-reader my-custom-reader})
```

I originally thought I might have been able to achieve this by binding `*data-readers*`, but it turns out that the underlying edn reader doesn't allow for that (probably with good reason).

I would be happy to do the implementation for you to have a look at.

What do you think?

**Comment by james-henderson** [comment]
I've solved this in [Phoenix](https://github.com/james-henderson/phoenix) by making the `edn/read-string` call take `*data-readers*` (and, by extension, data_readers.clj) into account - more than happy to do the same here if need be. What do you think would be the best option?

Certainly happy to have a PR! Cheers

**Comment by lloydshark** [comment]
Hi James, thanks for the response.

My opinion (though not strong) I think it is more flexible if you allow them to be optionally passed in.

That way you know explicitly what is legal for your config file. If you really want *data-readers* to be consulted you can still pass it in.

**Comment by james-henderson** [comment]
Yep, good point - so would you have them passed in as an optional extra argument to `defconfig`, say?

**Comment by lloydshark** [comment]
Yes, I was probably thinking an optional keyword argument... (just in case you ever want to add other optional parameters to defconfig) so the defconfig macro could be like the following.

`(defmacro defconfig [name file-or-resource & {:keys [custom-data-readers]}]`

When supplied they would be merged with the existing nomad data readers.

**Comment by james-henderson** [comment]
I've just released 0.7.1-SNAPSHOT, which now takes `*data-readers*` into account. `defconfig` also takes an extra optional parameter:

```clojure
(defconfig my-config (io/resource "...") {:data-readers {'my-reader/reader-type parse-reader-type}})
```

Let me know what you think :) 

Cheers,

James

**Comment by lloydshark** [comment]
Thanks James - you beat me to it... I started on the code last night.  I'll try it out (hopefully today).

**Comment by lloydshark** [comment]
OK, tried it out - I got the following error:

`Caused by: java.lang.RuntimeException: No such var: nomad/data-readers`

I think there's a missing ~ in front of data-readers in the defconfig macro.

**Comment by james-henderson** [comment]
Thanks Lloyd, sorry for that :/ 
Have pushed another snapshot. 

James

**Comment by lloydshark** [comment]
No trouble. I should have a chance today to try it out.

**Comment by lloydshark** [comment]
Thanks for that. Looks good to me, worked for my simple test cases. 

I tried specifying the optional extra parameter, and then without it.  I didn't try binding `*data-readers*` directly.

**Comment by lloydshark** [comment]
Hi James,

I'm wondering whether this change is likely to make it into the main release anytime soon. It certainly works for our needs.

Are you waiting for feedback on issue #19 before you would consider releasing it ?

- Boyd

**Comment by james-henderson** [comment]
Sorry - had forgotten about this - I've just a 0.7.1 release. Let me know what you think :)

James

**Comment by lloydshark** [comment]
Hey no trouble. Will integrate into our main development line soon. Thanks again.

**Comment by james-henderson** [comment]
No worries, thanks for your suggestion!
